/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_suapp_dailycast_zeus_util_CipherUtils */

#ifndef _Included_com_suapp_miss_weather_core_utils_CipherUtils
#define _Included_com_suapp_miss_weather_core_utils_CiplerUtils

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_suapp_miss_weather_core_utils_CiplerUtils
 * Method:    getAESKey
 * Signature: (Landroid/content/Context;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_suapp_dcdownloader_utils_CipherUtils_getAESKeyNative
        (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif