/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_suapp_miss_weather_core_utils_UDIDUtils */

#ifndef _Included_com_suapp_miss_weather_core_utils_UDIDUtils
#define _Included_com_suapp_miss_weather_core_utils_UDIDUtils
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_suapp_miss_weather_core_utils_UDIDUtils
 * Method:    generateUDID
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_suapp_dcdownloader_utils_UDIDUtils_generateUDIDNative
        (JNIEnv *, jclass, jstring);

/*
 * Class:     com_suapp_miss_weather_core_utils_UDIDUtils
 * Method:    isUDIDValid
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_suapp_dcdownloader_utils_utils_UDIDUtils_isUDIDValidNative
        (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
